openapi: 3.1.0
info:
  title: Generic Admin Resources API
  version: 1.0.0
servers:
  - url: http://localhost:3400/api/v1/admin
components:
  securitySchemes:
    SessionAuth:
      type: apiKey
      in: cookie
      name: hotel_session
  schemas:
    ErrorResponse:
      type: object
      required: [code, message]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: object, nullable: true }
    Pagination:
      type: object
      properties:
        page: { type: integer }
        limit: { type: integer }
        total: { type: integer }
        totalPages: { type: integer }
security:
  - SessionAuth: []
paths:
  /resources/{resource}:
    get:
      operationId: genericList
      description: REQ-API-GEN-001 テナント分離 + 権限チェック + 検索/並び替え/ページ
      parameters:
        - in: path
          name: resource
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: includeDeleted
          schema: { type: boolean, default: false }
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
    post:
      operationId: genericCreate
      description: REQ-API-GEN-002 作成（権限/テナント検証）
      parameters:
        - in: path
          name: resource
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '201': { description: Created }
        '400': { description: Validation Error }
        '403': { description: Forbidden }
  /resources/{resource}/{id}:
    get:
      operationId: genericGet
      description: REQ-API-GEN-003 詳細（テナント/権限）
      parameters:
        - in: path
          name: resource
          required: true
          schema: { type: string }
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
        '404': { description: Not Found }
    put:
      operationId: genericUpdate
      description: REQ-API-GEN-004 更新（権限/テナント）
      parameters:
        - in: path
          name: resource
          required: true
          schema: { type: string }
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
      responses:
        '200': { description: OK }
        '400': { description: Validation Error }
        '404': { description: Not Found }
    delete:
      operationId: genericDelete
      description: REQ-API-GEN-005 削除（ソフトデリート）
      parameters:
        - in: path
          name: resource
          required: true
          schema: { type: string }
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: No Content }
        '404': { description: Not Found }


