// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/Users/kaneko/node_modules/.pnpm/@sidebase+nuxt-auth@1.0.0_better-sqlite3@9.6.0_drizzle-orm@0.30.10_@opentelemetry+api@1_f76250a56add35b342a320983a0b369b/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
