// AUTO-GENERATED BY @sidebase/nuxt-auth
import { RouteOptions } from '/Users/kaneko/node_modules/.pnpm/@sidebase+nuxt-auth@1.0.0_better-sqlite3@9.6.0_drizzle-orm@0.30.10_@opentelemetry+api@1_f76250a56add35b342a320983a0b369b/node_modules/@sidebase/nuxt-auth/dist/runtime/types.ts'
declare module 'nitropack' {
  interface NitroRouteRules {
    auth?: RouteOptions
  }
  interface NitroRouteConfig {
    auth?: RouteOptions
  }
}
