// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/healthz': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/healthz.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.1_vite@6.4.1_@types+node@22.15.14_jiti@2.6.1_terser@5.44_50bcbcbb6ff82ca049e8db623e5f2a12/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}