// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.6.1_magicast@0.5.2_typescript@5.9.3_vue@3.5.13_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.6_@types+node@22.15.14_@vue+compiler-sfc@3.5.29_cac@6.7_994b311f10c443168fa1b4fd2c511a75/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.6.1_magicast@0.5.2_typescript@5.9.3_vue@3.5.13_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.2_vite@7.3.1_@types+node@22.15.14_jiti@2.6.1_terser@5.46_408134713a795913125fb426e1fcbc85/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@sidebase+nuxt-auth@1.0.0_encoding@0.1.13_magicast@0.5.2_next-auth@4.21.1_next@13.5.11__96f21fb9bd86861fb264c5d4e553a3fa/node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | '@nuxt/icon'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
