// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/@pinia+nuxt@0.6.1_magicast@0.5.1_typescript@5.9.3_vue@3.5.13_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_@types+node@22.15.14_better-sqlite3@9.6.0_cac@6.7.14__a84d73a4b1e12fc0a7f950236a6e6a28/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@pinia+nuxt@0.6.1_magicast@0.5.1_typescript@5.9.3_vue@3.5.13_typescript@5.9.3_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.1_vite@6.4.1_@types+node@22.15.14_jiti@2.6.1_terser@5.44_50bcbcbb6ff82ca049e8db623e5f2a12/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@sidebase+nuxt-auth@1.0.0_better-sqlite3@9.6.0_drizzle-orm@0.30.10_@opentelemetry+api@1_f76250a56add35b342a320983a0b369b/node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | '@nuxt/icon'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
