version: '3.8'

services:
  # hotel-saas サービス
  saas:
    build:
      context: ../hotel-saas
      dockerfile: Dockerfile
      target: build
    working_dir: /app
    volumes:
      - ../hotel-saas:/app
      - saas_node_modules:/app/node_modules
    command: sh -c "pnpm install && pnpm dev --port 3100 --host 0.0.0.0"
    env_file: .env.dev
    environment:
      - NODE_ENV=development
      - NUXT_PORT=3100
      - NUXT_HOST=0.0.0.0
    ports:
      - "3100:3100"
    depends_on:
      - db
      - redis
      - rabbitmq
      - common

  # hotel-common サービス
  common:
    build:
      context: ../hotel-common
      dockerfile: Dockerfile
      target: build
    working_dir: /app
    volumes:
      - ../hotel-common:/app
      - common_node_modules:/app/node_modules
    command: sh -c "npm install && ts-node-dev --transpile-only --no-notify src/main.ts"
    env_file: .env.dev
    environment:
      - NODE_ENV=development
      - PORT=3400
    ports:
      - "3400:3400"
    depends_on:
      - db
      - redis
      - rabbitmq

  # PostgreSQL データベース
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=hotel_app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotel_unified_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis キャッシュ
  redis:
    image: redis:8.2.0
    ports:
      - "6379:6379"
    command: redis-server --requirepass password

  # RabbitMQ メッセージキュー
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=hotel_app
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  saas_node_modules:
  common_node_modules:
  pgdata: