/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 顧客一覧取得 */
        get: operations["getCustomers"];
        put?: never;
        /** 顧客作成 */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 顧客詳細取得 */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 顧客情報更新 */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予約一覧取得 */
        get: operations["getReservations"];
        put?: never;
        /** 予約作成 */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス一覧取得 */
        get: operations["getServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** サービス注文作成 */
        post: operations["createServiceOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 顧客ポイント履歴取得 */
        get: operations["getCustomerPoints"];
        put?: never;
        /** ポイント追加/使用 */
        post: operations["addPoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** スタッフ一覧取得（管理者用） */
        get: operations["getAdminStaffList"];
        put?: never;
        /** スタッフ作成（管理者用） */
        post: operations["createAdminStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** スタッフ詳細取得（管理者用） */
        get: operations["getAdminStaff"];
        put?: never;
        post?: never;
        /** スタッフ削除（管理者用） */
        delete: operations["deleteAdminStaff"];
        options?: never;
        head?: never;
        /** スタッフ情報更新（管理者用） */
        patch: operations["updateAdminStaff"];
        trace?: never;
    };
    "/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** スタッフ詳細取得 */
        get: operations["getStaff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code?: string;
            message?: string;
            details?: Record<string, never>;
        };
        Pagination: {
            total?: number;
            page?: number;
            pageSize?: number;
            totalPages?: number;
        };
        Customer: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            memberId?: string | null;
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            address?: Record<string, never> | null;
            /** Format: date */
            birthdate?: string | null;
            /** @enum {string|null} */
            gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY" | null;
            nationality?: string | null;
            preferences?: Record<string, never> | null;
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            membership?: components["schemas"]["Membership"];
        };
        CustomerCreate: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: Record<string, never>;
            /** Format: date */
            birthdate?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
            nationality?: string;
            preferences?: Record<string, never>;
            notes?: string;
        };
        CustomerUpdate: {
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: Record<string, never>;
            /** Format: date */
            birthdate?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
            nationality?: string;
            preferences?: Record<string, never>;
            notes?: string;
        };
        Membership: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            rankId?: string;
            totalPoints?: number;
            availablePoints?: number;
            /** Format: date-time */
            registeredAt?: string;
            /** Format: date-time */
            expiresAt?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "EXPIRED" | "SUSPENDED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            rank?: components["schemas"]["MembershipRank"];
        };
        MembershipRank: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            name?: string;
            level?: number;
            pointThreshold?: number;
            benefits?: Record<string, never>;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Point: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            tenantId?: string;
            /** @enum {string} */
            type?: "EARN" | "USE" | "BONUS" | "ADJUSTMENT" | "EXPIRED";
            amount?: number;
            balance?: number;
            description?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            relatedEntityType?: string | null;
            relatedEntityId?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        PointCreate: {
            /** Format: uuid */
            customerId: string;
            /** @enum {string} */
            type: "EARN" | "USE" | "BONUS" | "ADJUSTMENT";
            amount: number;
            description?: string;
            /** Format: date-time */
            expiresAt?: string;
            relatedEntityType?: string;
            relatedEntityId?: string;
        };
        Reservation: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            reservationNumber?: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            roomId?: string;
            /** Format: date-time */
            checkInDate?: string;
            /** Format: date-time */
            checkOutDate?: string;
            adults?: number;
            children?: number;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELED" | "NO_SHOW";
            /** @enum {string} */
            origin?: "MEMBER" | "OTA" | "FRONT" | "PHONE" | "WALK_IN";
            specialRequests?: string | null;
            totalAmount?: number;
            /** Format: uuid */
            createdById?: string;
            /** Format: uuid */
            updatedById?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            customer?: components["schemas"]["Customer"];
            room?: components["schemas"]["Room"];
        };
        ReservationCreate: {
            /** Format: uuid */
            customerId: string;
            /** Format: uuid */
            roomId: string;
            /** Format: date-time */
            checkInDate: string;
            /** Format: date-time */
            checkOutDate: string;
            adults: number;
            children?: number;
            /** @enum {string} */
            origin: "MEMBER" | "OTA" | "FRONT" | "PHONE" | "WALK_IN";
            specialRequests?: string;
        };
        ReservationUpdate: {
            /** Format: uuid */
            roomId?: string;
            /** Format: date-time */
            checkInDate?: string;
            /** Format: date-time */
            checkOutDate?: string;
            adults?: number;
            children?: number;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELED" | "NO_SHOW";
            specialRequests?: string;
        };
        Room: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            roomNumber?: string;
            /** Format: uuid */
            roomTypeId?: string;
            /** Format: uuid */
            roomGradeId?: string | null;
            floor?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "OCCUPIED" | "CLEANING" | "MAINTENANCE" | "OUT_OF_ORDER";
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            roomType?: components["schemas"]["RoomType"];
            roomGrade?: components["schemas"]["RoomGrade"];
        };
        RoomType: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            name?: string;
            description?: string | null;
            capacity?: number;
            amenities?: Record<string, never> | null;
            images?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RoomGrade: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            roomTypeId?: string;
            name?: string;
            description?: string | null;
            priceMultiplier?: number;
            benefits?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Service: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            name?: string;
            description?: string | null;
            /** @enum {string} */
            category?: "FOOD" | "BEVERAGE" | "AMENITY" | "SPA" | "CLEANING" | "TRANSPORT" | "OTHER";
            price?: number;
            taxRate?: number;
            images?: Record<string, never> | null;
            availability?: Record<string, never> | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SEASONAL";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ServiceOrder: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            serviceId?: string;
            /** Format: uuid */
            roomId?: string | null;
            /** Format: uuid */
            customerId?: string | null;
            quantity?: number;
            /** @enum {string} */
            status?: "PENDING" | "PROCESSING" | "COMPLETED" | "CANCELED";
            /** Format: date-time */
            requestedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
            amount?: number;
            notes?: string | null;
            service?: components["schemas"]["Service"];
        };
        ServiceOrderCreate: {
            /** Format: uuid */
            serviceId: string;
            /** Format: uuid */
            roomId?: string;
            /** Format: uuid */
            customerId?: string;
            quantity: number;
            notes?: string;
        };
        Billing: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            reservationId?: string;
            billingNumber?: string;
            /** @enum {string} */
            status?: "PENDING" | "PARTIAL" | "PAID" | "OVERDUE" | "CANCELED" | "REFUNDED";
            totalAmount?: number;
            paidAmount?: number;
            /** Format: date-time */
            dueDate?: string | null;
            /** @enum {string|null} */
            paymentMethod?: "CASH" | "CREDIT_CARD" | "BANK_TRANSFER" | "POINTS" | "OTHER" | null;
            /** Format: date-time */
            paymentDate?: string | null;
            items?: Record<string, never>;
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BillingCreate: {
            /** Format: uuid */
            reservationId: string;
            /** Format: date-time */
            dueDate?: string;
            items: Record<string, never>;
            notes?: string;
        };
        BillingPayment: {
            amount: number;
            /** @enum {string} */
            paymentMethod: "CASH" | "CREDIT_CARD" | "BANK_TRANSFER" | "POINTS" | "OTHER";
            /** Format: date-time */
            paymentDate?: string;
            notes?: string;
        };
        Feedback: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            customerId?: string;
            entityType?: string;
            entityId?: string;
            rating?: number;
            comment?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        FeedbackCreate: {
            /** Format: uuid */
            customerId: string;
            entityType: string;
            entityId: string;
            rating: number;
            comment?: string;
        };
        Staff: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            staffCode?: string;
            staffNumber?: string;
            lastName?: string;
            firstName?: string;
            lastNameKana?: string | null;
            firstNameKana?: string | null;
            displayName?: string;
            employeeId?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: date-time */
            emailVerifiedAt?: string | null;
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** @default 0 */
            failedLoginCount: number;
            /** Format: date-time */
            lockedUntil?: string | null;
            /** Format: uuid */
            defaultRoleId?: string | null;
            /** @default 1 */
            baseLevel: number;
            departmentCode?: string | null;
            positionTitle?: string | null;
            /** Format: date */
            hireDate?: string | null;
            /**
             * @default full_time
             * @enum {string}
             */
            employmentType: "full_time" | "part_time" | "contract" | "temporary";
            /**
             * @default active
             * @enum {string}
             */
            employmentStatus: "active" | "inactive" | "suspended" | "terminated";
            /** Format: date */
            terminationDate?: string | null;
            terminationReason?: string | null;
            phoneNumber?: string | null;
            emergencyContact?: Record<string, never> | null;
            address?: Record<string, never> | null;
            photoUrl?: string | null;
            bio?: string | null;
            skills?: Record<string, never> | null;
            shiftPattern?: string | null;
            hourlyRate?: number | null;
            salary?: number | null;
            /** Format: uuid */
            supervisorId?: string | null;
            /** @default {} */
            accessRestrictions: Record<string, never>;
            /** @default {} */
            notificationSettings: Record<string, never>;
            /** @default {} */
            uiPreferences: Record<string, never>;
            securityClearance?: string | null;
            accessCardId?: string | null;
            /** @default true */
            isActive: boolean;
            /** @default false */
            isSystemUser: boolean;
            notes?: string | null;
            /** Format: uuid */
            hotelCommonUserId?: string | null;
            legacyUserData?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            createdBy?: string | null;
            /** Format: uuid */
            updatedBy?: string | null;
            /** Format: date-time */
            deletedAt?: string | null;
        };
        StaffSummary: {
            /** Format: uuid */
            id?: string;
            staffCode?: string;
            staffNumber?: string;
            displayName?: string;
            /** Format: email */
            email?: string | null;
            departmentCode?: string | null;
            positionTitle?: string | null;
            baseLevel?: number;
            /** @enum {string} */
            employmentStatus?: "active" | "inactive" | "suspended" | "terminated";
            /** Format: date-time */
            lastLoginAt?: string | null;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        StaffCreate: {
            lastName: string;
            firstName: string;
            lastNameKana?: string;
            firstNameKana?: string;
            displayName: string;
            staffCode: string;
            staffNumber: string;
            employeeId?: string;
            /** Format: email */
            email?: string;
            departmentCode?: string;
            positionTitle?: string;
            baseLevel?: number;
            /** @enum {string} */
            employmentType?: "full_time" | "part_time" | "contract" | "temporary";
            /** Format: date */
            hireDate?: string;
            phoneNumber?: string;
            emergencyContact?: Record<string, never>;
            address?: Record<string, never>;
            bio?: string;
            skills?: Record<string, never>;
            shiftPattern?: string;
            hourlyRate?: number;
            salary?: number;
            /** Format: uuid */
            supervisorId?: string;
            notes?: string;
        };
        StaffUpdate: {
            lastName?: string;
            firstName?: string;
            lastNameKana?: string;
            firstNameKana?: string;
            displayName?: string;
            /** Format: email */
            email?: string;
            departmentCode?: string;
            positionTitle?: string;
            baseLevel?: number;
            /** @enum {string} */
            employmentType?: "full_time" | "part_time" | "contract" | "temporary";
            /** @enum {string} */
            employmentStatus?: "active" | "inactive" | "suspended" | "terminated";
            /** Format: date */
            terminationDate?: string;
            terminationReason?: string;
            phoneNumber?: string;
            emergencyContact?: Record<string, never>;
            address?: Record<string, never>;
            bio?: string;
            skills?: Record<string, never>;
            shiftPattern?: string;
            hourlyRate?: number;
            salary?: number;
            /** Format: uuid */
            supervisorId?: string;
            accessRestrictions?: Record<string, never>;
            notificationSettings?: Record<string, never>;
            uiPreferences?: Record<string, never>;
            securityClearance?: string;
            accessCardId?: string;
            isActive?: boolean;
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCustomers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 顧客一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Customer"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description 顧客作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 顧客詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 顧客が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description 顧客更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 顧客が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReservations: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: "PENDING" | "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELED" | "NO_SHOW";
                fromDate?: string;
                toDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 予約一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Reservation"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description 予約作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 部屋の二重予約 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getServices: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: "FOOD" | "BEVERAGE" | "AMENITY" | "SPA" | "CLEANING" | "TRANSPORT" | "OTHER";
                status?: "ACTIVE" | "INACTIVE" | "SEASONAL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サービス一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Service"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createServiceOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ServiceOrderCreate"];
            };
        };
        responses: {
            /** @description サービス注文作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOrder"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerPoints: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ポイント履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Point"][];
                        pagination?: components["schemas"]["Pagination"];
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 顧客が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addPoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PointCreate"];
            };
        };
        responses: {
            /** @description ポイント操作成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Point"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 顧客が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAdminStaffList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description 名前、メールアドレス、スタッフコードで検索 */
                search?: string;
                /** @description 部門コードでフィルタリング */
                departmentCode?: string;
                /** @description 雇用ステータスでフィルタリング */
                employmentStatus?: "active" | "inactive" | "suspended" | "terminated";
                /** @description 権限レベルでフィルタリング */
                baseLevel?: number;
                /** @description ソート項目 */
                sortBy?: "displayName" | "staffCode" | "departmentCode" | "baseLevel" | "lastLoginAt" | "createdAt";
                /** @description ソート順序 */
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スタッフ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["StaffSummary"][];
                        pagination?: components["schemas"]["Pagination"];
                        summary?: {
                            totalStaff?: number;
                            activeStaff?: number;
                            inactiveStaff?: number;
                            departmentCounts?: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 権限不足（管理者権限が必要） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAdminStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            /** @description スタッフ作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 権限不足（管理者権限が必要） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 重複エラー（スタッフコード、メールアドレス等） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAdminStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スタッフ詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 権限不足（管理者権限が必要） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description スタッフが見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteAdminStaff: {
        parameters: {
            query?: {
                /** @description ソフト削除フラグ（デフォルト：true） */
                soft?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スタッフ削除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        message?: string;
                        /** Format: date-time */
                        deletedAt?: string | null;
                    };
                };
            };
            /** @description 削除不可（システムユーザー等） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 権限不足（管理者権限が必要） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description スタッフが見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateAdminStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StaffUpdate"];
            };
        };
        responses: {
            /** @description スタッフ更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 権限不足（管理者権限が必要） */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description スタッフが見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 重複エラー（メールアドレス等） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スタッフ詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description スタッフが見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
