// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/5/2026, 5:07:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/yuji/Developer/hotel-kanri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/plugins/**/*.{js,ts,mjs}","/Users/yuji/Developer/hotel-kanri/composables/**/*.{js,ts,mjs}","/Users/yuji/Developer/hotel-kanri/composables/**/**/*.{js,ts,mjs}","/Users/yuji/Developer/hotel-kanri/utils/**/**/*.{js,ts,mjs}","/Users/yuji/Developer/hotel-kanri/utils/**/*.{js,ts,mjs}","/Users/yuji/Developer/hotel-kanri/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yuji/Developer/hotel-kanri/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;