// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/11 16:21:18
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/kaneko/hotel-kanri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/plugins/**/*.{js,ts,mjs}","/Users/kaneko/hotel-kanri/composables/**/*.{js,ts,mjs}","/Users/kaneko/hotel-kanri/composables/**/**/*.{js,ts,mjs}","/Users/kaneko/hotel-kanri/utils/**/**/*.{js,ts,mjs}","/Users/kaneko/hotel-kanri/utils/**/*.{js,ts,mjs}","/Users/kaneko/hotel-kanri/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kaneko/hotel-kanri/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;