name: ブランチ作成ワークフロー

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'ブランチタイプ'
        required: true
        default: 'feature'
        type: choice
        options:
          - feature
          - bugfix
          - hotfix
          - release
          - docs
      branch_name:
        description: 'ブランチ名（タイプは自動追加）'
        required: true
        type: string
      base_branch:
        description: '基点ブランチ'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - main
          - production

jobs:
  create-branch:
    name: ブランチの作成
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.base_branch }}

      - name: 基点ブランチの更新
        run: |
          git pull origin ${{ github.event.inputs.base_branch }}

      - name: ブランチの作成
        run: |
          BRANCH="${{ github.event.inputs.branch_type }}/${{ github.event.inputs.branch_name }}"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: ブランチ作成完了通知
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "good",
                  "text": "新しいブランチが作成されました: ${{ env.BRANCH_NAME }} (基点ブランチ: ${{ github.event.inputs.base_branch }})"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}