name: ドキュメント検証

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '**.md'

jobs:
  markdown-lint:
    name: Markdown リンター
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Markdown リンターのセットアップ
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.json
          ignore_files: "node_modules/**"

  broken-links:
    name: リンク切れチェック
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: リンク切れチェックのセットアップ
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/mlc_config.json'
          folder-path: 'docs'
          max-depth: -1

  spellcheck:
    name: スペルチェック
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: スペルチェックのセットアップ
        uses: rojopolis/spellcheck-github-actions@0.28.0
        with:
          config_path: .github/workflows/spellcheck.yml
          task_name: Markdown

  notify:
    name: 通知
    runs-on: ubuntu-latest
    needs: [markdown-lint, broken-links, spellcheck]
    if: ${{ failure() }}
    steps:
      - name: Slack通知
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}