name: Quality (OpenAPI & SSOT)

on:
  pull_request:
  workflow_dispatch:

jobs:
  openapi-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Install spectral
        run: |
          npm install -g @stoplight/spectral-cli js-yaml

      - name: Lint OpenAPI (staff-management)
        run: spectral lint docs/03_ssot/openapi/staff-management.yaml

      - name: Lint OpenAPI (generic-resources)
        run: spectral lint docs/03_ssot/openapi/generic-resources.yaml

      - name: Check requirement coverage (STAFF IDs)
        run: node scripts/check-requirement-coverage.js

name: Quality
on: [pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm openapi:gen
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test
      - run: node scripts/guardrails/check-api-routes.mjs
      - run: node scripts/guardrails/check-openapi-consistency.mjs

