name: Spellcheck

on:
  push:
    branches: [main, develop]
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          config_path: .github/.pyspelling.yml
          task_name: Markdown
